### ISSUE TITLE
elk mrtree hierarchical layout

### ISSUE THREAD

**Issue by timscorbett** [cytoscape/cytoscape.js-elk#46]
The following does not give me mrtree layout shown here
https://cytoscape.org/cytoscape.js-elk/?demo=mrtree

import CytoscapeComponent from "react-cytoscapejs";
import Cytoscape from "cytoscape";
import elk from "cytoscape-elk";
Cytoscape.use(elk);

const layout = {
    name: "elk",
    fit: true,
    // circle: true,
    directed: true,
    padding: 50,
    // spacingFactor: 1.5,
    //animate: false,
    //animationDuration: 1000,
    avoidOverlap: true,
    nodeDimensionsIncludeLabels: true,
    elk: {
      // All options are available at http://www.eclipse.org/elk/reference.html
      "elk.direction": "DOWN",
      "algorithm": "mrtree",
    },
  };

**Comment by maxkfranz** [comment]
Have you cross-posted the issue on react-cytoscape?  Since the demo works here, the problem may be over there. On Aug 14, 2023, at 14:19, timscorbett ***@***.***> wrote:﻿
The following does not give me mrtree layout shown here
https://cytoscape.org/cytoscape.js-elk/?demo=mrtree
import CytoscapeComponent from "react-cytoscapejs";
import Cytoscape from "cytoscape";
import elk from "cytoscape-elk";
Cytoscape.use(elk);
const layout = {
name: "elk",
fit: true,
// circle: true,
directed: true,
padding: 50,
// spacingFactor: 1.5,
//animate: false,
//animationDuration: 1000,
avoidOverlap: true,
nodeDimensionsIncludeLabels: true,
elk: {
// All options are available at http://www.eclipse.org/elk/reference.html
"elk.direction": "DOWN",
"algorithm": "mrtree",
},
};
